// Generated by CoffeeScript 1.6.2
(function() {
  var Button, Channel, ChannelCollection, ChannelListItem, Collection, ListItem, ListView, MessageListItem, Model, NewMessageForm, StringInput, View, activateChannel, active_channel, active_channel_messages, channel_collection, setUpInterface, withinRange, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ref = window.Doodad, Button = _ref.Button, StringInput = _ref.StringInput;

  _ref1 = window.Backbone, View = _ref1.View, Model = _ref1.Model, Collection = _ref1.Collection;

  Channel = (function(_super) {
    __extends(Channel, _super);

    function Channel() {
      this.sendNewMessage = __bind(this.sendNewMessage, this);      _ref2 = Channel.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    Channel.prototype.sendNewMessage = function(body, cb) {
      console.log(this.get('messages_url'), body);
      return $.post(this.get('messages_url'), {
        body: body
      }, function(success) {
        active_channel_messages.fetch();
        return cb();
      });
    };

    Channel.prototype.getType = function() {
      if (this.get('has_inbox')) {
        if (this.get('has_outbox')) {
          return 'message';
        }
        return 'subscription';
      }
      return 'broadcast';
    };

    return Channel;

  })(Model);

  ChannelCollection = (function(_super) {
    __extends(ChannelCollection, _super);

    function ChannelCollection() {
      _ref3 = ChannelCollection.__super__.constructor.apply(this, arguments);
      return _ref3;
    }

    ChannelCollection.prototype.model = Channel;

    return ChannelCollection;

  })(Collection);

  active_channel = null;

  channel_collection = new ChannelCollection();

  channel_collection.url = '/channels';

  channel_collection.on('sync', function() {
    return console.log('reset!', channel_collection);
  });

  ListItem = (function(_super) {
    __extends(ListItem, _super);

    function ListItem() {
      _ref4 = ListItem.__super__.constructor.apply(this, arguments);
      return _ref4;
    }

    ListItem.prototype.className = 'ListItem';

    ListItem.prototype.tagName = 'li';

    ListItem.prototype.render = function() {
      return this.el;
    };

    return ListItem;

  })(View);

  ChannelListItem = (function(_super) {
    __extends(ChannelListItem, _super);

    function ChannelListItem() {
      _ref5 = ChannelListItem.__super__.constructor.apply(this, arguments);
      return _ref5;
    }

    ChannelListItem.prototype.render = function() {
      if (this.model.get('has_inbox')) {
        this.$el.addClass('has_inbox');
      }
      if (this.model.get('has_outbox')) {
        this.$el.addClass('has_outbox');
      }
      this.$el.text(this.model.get('name'));
      return ChannelListItem.__super__.render.apply(this, arguments);
    };

    ChannelListItem.prototype.events = {
      'click': '_activate'
    };

    ChannelListItem.prototype._activate = function() {
      $("." + this.className + ".active").removeClass('active');
      this.$el.addClass('active');
      return activateChannel(this.model);
    };

    return ChannelListItem;

  })(ListItem);

  MessageListItem = (function(_super) {
    __extends(MessageListItem, _super);

    function MessageListItem() {
      _ref6 = MessageListItem.__super__.constructor.apply(this, arguments);
      return _ref6;
    }

    MessageListItem.prototype.render = function() {
      var _format;

      this.$el.addClass("box-" + (this.model.get('box')));
      _format = function(date) {
        var d, _pad;

        d = new Date(date);
        _pad = function(n) {
          if (n < 10) {
            return "0" + n;
          }
          return "" + n;
        };
        return "" + (d.getFullYear()) + "-" + (d.getMonth() + 1) + "-" + (d.getDate()) + " " + (d.getHours()) + ":" + (_pad(d.getMinutes())) + ":" + (_pad(d.getSeconds()));
      };
      this.$el.html("<div class=\"body\">\n    " + (markdown.toHTML(this.model.get('body'))) + "\n</div>\n<time datetime=\"" + (this.model.get('date')) + "\">" + (_format(this.model.get('date'))) + "</time>");
      return this.el;
    };

    return MessageListItem;

  })(ListItem);

  ListView = (function(_super) {
    __extends(ListView, _super);

    function ListView() {
      this.render = __bind(this.render, this);      _ref7 = ListView.__super__.constructor.apply(this, arguments);
      return _ref7;
    }

    ListView.prototype.className = 'ListView';

    ListView.prototype.tagName = 'ul';

    ListView.prototype.initialize = function(opts) {
      this._collection = opts.collection;
      if (opts.item_view) {
        this._item_view = opts.item_view;
      } else {
        this._item_view = ListItem;
      }
      if (opts.filter != null) {
        this._list_filter = opts.filter;
      } else {
        this._list_filter = function() {
          return true;
        };
      }
      return this.listenTo(this._collection, 'sync', this.render);
    };

    ListView.prototype.render = function() {
      var _this = this;

      this.$el.empty();
      this._collection.each(function(item) {
        var item_view;

        if (_this._list_filter(item)) {
          item_view = new _this._item_view({
            model: item
          });
          return _this.$el.append(item_view.render());
        }
      });
      return this.el;
    };

    return ListView;

  })(View);

  withinRange = function(n, min, max) {
    if (n < min) {
      return min;
    }
    if (n > max) {
      return max;
    }
    return n;
  };

  active_channel = new Channel();

  active_channel_messages = new Collection();

  activateChannel = function(channel) {
    active_channel.set(channel.toJSON());
    active_channel_messages.url = active_channel.get('messages_url');
    return active_channel_messages.fetch();
  };

  NewMessageForm = (function(_super) {
    __extends(NewMessageForm, _super);

    function NewMessageForm() {
      this.render = __bind(this.render, this);      _ref8 = NewMessageForm.__super__.constructor.apply(this, arguments);
      return _ref8;
    }

    NewMessageForm.prototype.initialize = function() {
      var MESSAGE_PANEL_DEFAULT_SIZE, new_message_field, send_message_button;

      this.listenTo(this.model, 'change', this.render);
      MESSAGE_PANEL_DEFAULT_SIZE = 50;
      new_message_field = new StringInput({
        multiline: true,
        placeholder: 'New message...',
        size: {
          width: '100%',
          height: MESSAGE_PANEL_DEFAULT_SIZE
        },
        on: {
          focus: function(si, val) {
            send_message_button.show();
            return _.defer(function() {
              var new_height;

              new_height = withinRange(si._ui.input[0].scrollHeight, 200, 500);
              return new_message_field.setSize({
                height: new_height
              });
            });
          },
          blur: function(si, val) {
            if (!val) {
              send_message_button.hide();
              return _.defer(function() {
                return new_message_field.setSize({
                  height: MESSAGE_PANEL_DEFAULT_SIZE
                });
              });
            }
          }
        },
        action: function(si, value) {
          var new_height;

          if (value) {
            new_height = withinRange(si._ui.input[0].scrollHeight, 200, 500);
            return _.defer(function() {
              send_message_button.enable();
              return new_message_field.setSize({
                height: new_height
              });
            });
          } else {
            send_message_button.disable();
            return new_message_field.setSize({
              height: MESSAGE_PANEL_DEFAULT_SIZE
            });
          }
        }
      });
      send_message_button = new Button({
        id: 'send_message_button',
        label: 'Send Message',
        spinner: true,
        enabled: false,
        action: function() {
          new_message_field.disable();
          return active_channel.sendNewMessage(new_message_field.value, function() {
            console.log('sent message');
            send_message_button.disable().hide();
            new_message_field.setValue('');
            return new_message_field.setSize({
              height: MESSAGE_PANEL_DEFAULT_SIZE
            });
          });
        }
      });
      this._new_message_field = new_message_field;
      this._send_message_button = send_message_button;
      return send_message_button.hide();
    };

    NewMessageForm.prototype.render = function() {
      if (this.model.getType() === 'subscription') {
        this.$el.hide();
      } else {
        this.$el.show();
      }
      this.$el.empty();
      this.$el.append(this._new_message_field.render());
      return this.$el.append(this._send_message_button.render());
    };

    return NewMessageForm;

  })(View);

  setUpInterface = function() {
    $('#app').html("<div id=\"panel_channels\">\n    <ul id=\"channel_messages\"></ul>\n    <ul id=\"channel_broadcasts\"></ul>\n    <ul id=\"channel_subscriptions\"></ul>\n</div>\n<div id=\"panel_messages\">\n    <h1 id=\"channel_title\"></h1>\n    <div id=\"new_message_form\"></div>\n    <ul id=\"channel_messages_list\"></ul>\n</div>");
    new ListView({
      collection: channel_collection,
      el: $('#channel_messages'),
      filter: function(c) {
        return c.getType() === 'message';
      },
      item_view: ChannelListItem
    });
    new ListView({
      collection: channel_collection,
      el: $('#channel_broadcasts'),
      filter: function(c) {
        return c.getType() === 'broadcast';
      },
      item_view: ChannelListItem
    });
    new ListView({
      collection: channel_collection,
      el: $('#channel_subscriptions'),
      filter: function(c) {
        return c.getType() === 'subscription';
      },
      item_view: ChannelListItem
    });
    new NewMessageForm({
      model: active_channel,
      el: $('#new_message_form')
    });
    return new ListView({
      collection: active_channel_messages,
      item_view: MessageListItem,
      el: $('#channel_messages_list')
    });
  };

  setUpInterface();

  channel_collection.fetch();

}).call(this);
